.\" Manual page for jura
.TH JURA 1 "November 2024 "5.0" "jura manual"
.SH NAME
jura -\ a small, lightweight terminal text editor
.SH SYNOPSIS
.B jura
[\fIoptions\fR] [\fIfilename\fR]
.SH DESCRIPTION
jura is a simple text editor that allows users to create and modify text files. It features syntax highlighting, line numbering, and basic editing functionalities.
.SH OPTIONS
.TP
.B \-h
show all options and help options
.TP
.B \-v version
prints the current version to the standard output


.SH EXAMPLE
.B jura 
creates a blank file and opens it in the editor

.B jura example.txt
opens the file example.txt in the editor if it exists

.SH AUTHOR
Nooberieno
.SH COPYRIGHT
this program is licensed under the MIT license under the Copyright (c) 2024 Nooberieno